"""empty message

Revision ID: 017c9c44fa7e
Revises: cf1cac419e72
Create Date: 2020-08-16 12:52:15.698554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '017c9c44fa7e'
down_revision = 'cf1cac419e72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['users.id'], )
    )
    op.drop_table('relationship')
    op.drop_table('friendship')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('friendship',
    sa.Column('user1_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user2_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user1_id'], ['users.id'], name='friendship_user1_id_fkey'),
    sa.ForeignKeyConstraint(['user2_id'], ['users.id'], name='friendship_user2_id_fkey'),
    sa.PrimaryKeyConstraint('user1_id', 'user2_id', name='friendship_pkey')
    )
    op.create_table('relationship',
    sa.Column('requesting_user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('receiving_user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['receiving_user_id'], ['users.id'], name='relationship_receiving_user_id_fkey'),
    sa.ForeignKeyConstraint(['requesting_user_id'], ['users.id'], name='relationship_requesting_user_id_fkey'),
    sa.PrimaryKeyConstraint('requesting_user_id', 'receiving_user_id', name='relationship_pkey')
    )
    op.drop_table('followers')
    # ### end Alembic commands ###
