"""empty message

Revision ID: 27930f7023a6
Revises: 6045282b8dfd
Create Date: 2020-08-16 16:25:23.773895

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '27930f7023a6'
down_revision = '6045282b8dfd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('diary', sa.Column('posted', sa.DateTime(), nullable=False))
    op.add_column('diary', sa.Column('tweet_id', sa.Integer(), nullable=False))
    op.add_column('diary', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'diary', 'users', ['user_id'], ['id'])
    op.drop_column('diary', 'id')
    op.drop_column('diary', 'date')
    op.drop_column('diary', 'username')
    op.drop_column('diary', 'id_per_user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('diary', sa.Column('id_per_user', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('diary', sa.Column('username', sa.VARCHAR(length=25), autoincrement=False, nullable=False))
    op.add_column('diary', sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('diary', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_constraint(None, 'diary', type_='foreignkey')
    op.drop_column('diary', 'user_id')
    op.drop_column('diary', 'tweet_id')
    op.drop_column('diary', 'posted')
    # ### end Alembic commands ###
