"""empty message

Revision ID: 6045282b8dfd
Revises: 017c9c44fa7e
Create Date: 2020-08-16 13:58:58.715650

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6045282b8dfd'
down_revision = '017c9c44fa7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('follower',
    sa.Column('who_id', sa.Integer(), nullable=False),
    sa.Column('whom_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('who_id', 'whom_id')
    )
    op.drop_table('followers')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('followed_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['users.id'], name='followers_followed_id_fkey'),
    sa.ForeignKeyConstraint(['follower_id'], ['users.id'], name='followers_follower_id_fkey')
    )
    op.drop_table('follower')
    # ### end Alembic commands ###
