"""empty message

Revision ID: 74841e0f8bd0
Revises: 6f6543f5d79f
Create Date: 2020-09-30 11:33:17.323962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74841e0f8bd0'
down_revision = '6f6543f5d79f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('image_file', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'image_file')
    # ### end Alembic commands ###
