"""empty message

Revision ID: c9bce0bff308
Revises: 223ea3b01dc3
Create Date: 2020-08-16 12:18:55.910772

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9bce0bff308'
down_revision = '223ea3b01dc3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('relationship',
    sa.Column('requesting_user_id', sa.Integer(), nullable=False),
    sa.Column('receiving_user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['receiving_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['requesting_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('requesting_user_id', 'receiving_user_id')
    )
    op.drop_table('friends')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('friends',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('friend_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['friend_id'], ['users.id'], name='friends_friend_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='friends_user_id_fkey')
    )
    op.drop_table('relationship')
    # ### end Alembic commands ###
